version: 0.2

env:
  parameter-store:
    user-docker-password: /my/docker-registry/password
    user-docker-username: /my/docker-registry/username
    user-docker-repositry-url: /my/docker-registry/URL
phases:
  install:
    runtime-versions:
      python: 3.13
      
  pre_build:
    commands:
      - echo "Installing Dependencies"
      - pip install -r day-14/simple-python-app/requirements.txt
      - echo "Logging Into Docker"
      - echo "$user-docker-password" | docker login -u "$user-docker-username" --password-stdin
  build:
    commands:
      - echo "Running Tests"
      - cd day-14/simple-python-app
      - docker build -t "user-docker-repositry-url/user-docker-username/docker-flask-app:latest" .
      - docker push "user-docker-repositry-url/user-docker-username/docker-flask-app:latest"
  post_build:
    commands:
      - echo "Build Is Successful"
